<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>egb</string>
		<string>egamebook</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl|echo|declare|init|functions|classes)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl|echo|declare|init|functions|classes)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>name</key>
	<string>Egamebook</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(&lt;(script|classes|declare|init|functions|/echo)&gt;)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.toplevel.egamebook</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^\s*&lt;(/script|/classes|/declare|/init|/functions|echo)&gt;\s*$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.toplevel.egamebook</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.source.dart.egamebook</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.dart</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(goto|repeatBlock|nextScript|echo|choice)(?=\()</string>
					<key>name</key>
					<string>support.function.egamebook</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(points|choices|vars)</string>
					<key>name</key>
					<string>support.variable.egamebook</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\$(\{\w[^\}]+\}|\w+)</string>
			<key>name</key>
			<string>variable.other.inline.egamebook</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=^Title:\s+\w)</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>metadata.egamebook</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.metadata.key.egamebook</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.metadata.value.egamebook</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^((\w+[\s\w]*):)?\s+(\w.*$)</string>
					<key>name</key>
					<string>metadata.line.egamebook</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=^\s*---+\s*\n)</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>newpage.egamebook</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*---+\s*\n</string>
					<key>name</key>
					<string>meta.separator.newpage.egamebook</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*[^-\[].*$</string>
					<key>name</key>
					<string>markup.heading.h1.egamebook</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(visitOnce)</string>
					<key>name</key>
					<string>support.constant.page.option.egamebook</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>TODO</string>
			<key>name</key>
			<string>keyword.other.todo.egamebook</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^-\s+((.+)\s+)?(\[)(&lt;&lt;&lt;)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.choice.egamebook</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.choice.egamebook</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant.choice.egamebook</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\{.+\})?\s*(.+)?\s*(\])\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.source.dart.egamebook</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading.h1.egamebook</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.choice.egamebook</string>
				</dict>
			</dict>
			<key>name</key>
			<string>choice.egamebook</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)
						(\*|_)(?=\S)								# Open
						(?=
							(
							    &lt;[^&gt;]*+&gt;							# HTML tags
							  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																	# Raw
							  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
							  | \[
								(				
								        (?&lt;square&gt;					# Named group
											[^\[\]\\]				# Match most chars
								          | \\.						# Escaped chars
								          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
								        )*+
									\]
									(
										(							# Reference Link
											[ ]?					# Optional space
											\[[^\]]*+\]				# Ref name
										)
									  | (							# Inline Link
											\(						# Opening paren
												[ \t]*+				# Optional whtiespace
												&lt;?(.*?)&gt;?			# URL
												[ \t]*+				# Optional whtiespace
												(					# Optional Title
													(?&lt;title&gt;['"])
													(.*?)
													\k&lt;title&gt;
												)?
											\)
										)
									)
								)
							  | \1\1								# Must be bold closer
							  | (?!(?&lt;=\S)\1).						# Everything besides
																	# style closer
							)++
							(?&lt;=\S)\1								# Close
						)
					</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)(\1)((?!\1)|(?=\1\1))</string>
			<key>name</key>
			<string>markup.italic.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?=&lt;[^&gt;]*?&gt;)</string>
					<key>end</key>
					<string>(?&lt;=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)
						(\*\*|__)(?=\S)								# Open
						(?=
							(
							    &lt;[^&gt;]*+&gt;							# HTML tags
							  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																	# Raw
							  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
							  | \[
								(				
								        (?&lt;square&gt;					# Named group
											[^\[\]\\]				# Match most chars
								          | \\.						# Escaped chars
								          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
								        )*+
									\]
									(
										(							# Reference Link
											[ ]?					# Optional space
											\[[^\]]*+\]				# Ref name
										)
									  | (							# Inline Link
											\(						# Opening paren
												[ \t]*+				# Optional whtiespace
												&lt;?(.*?)&gt;?			# URL
												[ \t]*+				# Optional whtiespace
												(					# Optional Title
													(?&lt;title&gt;['"])
													(.*?)
													\k&lt;title&gt;
												)?
											\)
										)
									)
								)
							  | (?!(?&lt;=\S)\1).						# Everything besides
																	# style closer
							)++
							(?&lt;=\S)\1								# Close
						)
					</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)(\1)</string>
			<key>name</key>
			<string>markup.bold.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?=&lt;[^&gt;]*?&gt;)</string>
					<key>end</key>
					<string>(?&lt;=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ampersand</key>
		<dict>
			<key>comment</key>
			<string>
				Markdown will convert this for us. We match it so that the
				HTML grammar will not mark it up as invalid.
			</string>
			<key>match</key>
			<string>&amp;(?!([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+);)</string>
			<key>name</key>
			<string>meta.other.valid-ampersand.markdown</string>
		</dict>
		<key>block_quote</key>
		<dict>
			<key>begin</key>
			<string>\G[ ]{,3}(&gt;)(?!$)[ ]?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.blockquote.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>
				We terminate the block quote when seeing an empty line, a
				separator or a line with leading &gt; characters. The latter is
				to “reset” the quote level for quoted lines.
			</string>
			<key>end</key>
			<string>(?x)^
				(?=	\s*$
				|	[ ]{,3}(?&lt;marker&gt;[-*_])([ ]{,2}\k&lt;marker&gt;){2,}[ \t]*+$
				|	[ ]{,3}&gt;.
				)</string>
			<key>name</key>
			<string>markup.quote.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)\G
						(?=	[ ]{,3}&gt;.
						)</string>
					<key>end</key>
					<string>^</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block_quote</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?x)\G
						(?=	([ ]{4}|\t)
						|	[#]{1,6}\s*+
						|	[ ]{,3}(?&lt;marker&gt;[-*_])([ ]{,2}\k&lt;marker&gt;){2,}[ \t]*+$
						)</string>
					<key>end</key>
					<string>^</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#heading</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#separator</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)\G
						(?!	$
						|	[ ]{,3}&gt;.
						|	([ ]{4}|\t)
						|	[#]{1,6}\s*+
						|	[ ]{,3}(?&lt;marker&gt;[-*_])([ ]{,2}\k&lt;marker&gt;){2,}[ \t]*+$
						)</string>
					<key>end</key>
					<string>$|(?&lt;=\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block_raw</key>
		<dict>
			<key>match</key>
			<string>\G([ ]{4}|\t).*$\n?</string>
			<key>name</key>
			<string>markup.raw.block.markdown</string>
		</dict>
		<key>bold</key>
		<dict>
			<key>begin</key>
			<string>(?x)
						(\*\*|__)(?=\S)								# Open
						(?=
							(
							    &lt;[^&gt;]*+&gt;							# HTML tags
							  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																	# Raw
							  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
							  | \[
								(				
								        (?&lt;square&gt;					# Named group
											[^\[\]\\]				# Match most chars
								          | \\.						# Escaped chars
								          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
								        )*+
									\]
									(
										(							# Reference Link
											[ ]?					# Optional space
											\[[^\]]*+\]				# Ref name
										)
									  | (							# Inline Link
											\(						# Opening paren
												[ \t]*+				# Optional whtiespace
												&lt;?(.*?)&gt;?			# URL
												[ \t]*+				# Optional whtiespace
												(					# Optional Title
													(?&lt;title&gt;['"])
													(.*?)
													\k&lt;title&gt;
												)?
											\)
										)
									)
								)
							  | (?!(?&lt;=\S)\1).						# Everything besides
																	# style closer
							)++
							(?&lt;=\S)\1								# Close
						)
					</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)(\1)</string>
			<key>name</key>
			<string>markup.bold.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?=&lt;[^&gt;]*?&gt;)</string>
					<key>end</key>
					<string>(?&lt;=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
		<key>bracket</key>
		<dict>
			<key>comment</key>
			<string>
				Markdown will convert this for us. We match it so that the
				HTML grammar will not mark it up as invalid.
			</string>
			<key>match</key>
			<string>&lt;(?![a-z/?\$!])</string>
			<key>name</key>
			<string>meta.other.valid-bracket.markdown</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\[-`*_#+.!(){}\[\]\\&gt;]</string>
			<key>name</key>
			<string>constant.character.escape.markdown</string>
		</dict>
		<key>heading</key>
		<dict>
			<key>begin</key>
			<string>\G(#{1,6})(?!#)\s*(?=\S)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.section.markdown</string>
			<key>end</key>
			<string>\s*(#*)$\n?</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>image-inline</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.markdown</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.markdown</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown</string>
				</dict>
				<key>14</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.markdown</string>
				</dict>
				<key>15</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.markdown</string>
				</dict>
				<key>16</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.whitespace.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.image.markdown</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x:
				\!							# Images start with !
				(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])	
											# Match the link text.
				([ ])?						# Space not allowed
				(\()						# Opening paren for url
					(&lt;?)(\S+?)(&gt;?)			# The url
					[ \t]*					# Optional whitespace
					(?:
						  ((\().+?(\)))		# Match title in parens…
						| ((").+?("))		# or in quotes.
					)?						# Title is optional
					\s*						# Optional whitespace
				(\))
			 )</string>
			<key>name</key>
			<string>meta.image.inline.markdown</string>
		</dict>
		<key>image-ref</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\!(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)(.*?)(\])</string>
			<key>name</key>
			<string>meta.image.reference.markdown</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
		<key>italic</key>
		<dict>
			<key>begin</key>
			<string>(?x)
						(\*|_)(?=\S)								# Open
						(?=
							(
							    &lt;[^&gt;]*+&gt;							# HTML tags
							  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																	# Raw
							  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
							  | \[
								(				
								        (?&lt;square&gt;					# Named group
											[^\[\]\\]				# Match most chars
								          | \\.						# Escaped chars
								          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
								        )*+
									\]
									(
										(							# Reference Link
											[ ]?					# Optional space
											\[[^\]]*+\]				# Ref name
										)
									  | (							# Inline Link
											\(						# Opening paren
												[ \t]*+				# Optional whtiespace
												&lt;?(.*?)&gt;?			# URL
												[ \t]*+				# Optional whtiespace
												(					# Optional Title
													(?&lt;title&gt;['"])
													(.*?)
													\k&lt;title&gt;
												)?
											\)
										)
									)
								)
							  | \1\1								# Must be bold closer
							  | (?!(?&lt;=\S)\1).						# Everything besides
																	# style closer
							)++
							(?&lt;=\S)\1								# Close
						)
					</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)(\1)((?!\1)|(?=\1\1))</string>
			<key>name</key>
			<string>markup.italic.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?=&lt;[^&gt;]*?&gt;)</string>
					<key>end</key>
					<string>(?&lt;=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
		<key>line-break</key>
		<dict>
			<key>match</key>
			<string> {2,}$</string>
			<key>name</key>
			<string>meta.dummy.line-break</string>
		</dict>
		<key>link-email</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;)((?:mailto:)?[-.\w]+@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)(&gt;)</string>
			<key>name</key>
			<string>meta.link.email.lt-gt.markdown</string>
		</dict>
		<key>link-inet</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;)((?:https?|ftp)://.*?)(&gt;)</string>
			<key>name</key>
			<string>meta.link.inet.markdown</string>
		</dict>
		<key>link-inline</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown</string>
				</dict>
				<key>14</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>15</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>16</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.whitespace.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x:
				(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])	
											# Match the link text.
				([ ])?						# Space not allowed
				(\()						# Opening paren for url
					(&lt;?)(.*?)(&gt;?)			# The url
					[ \t]*					# Optional whitespace
					(?:
						  ((\().+?(\)))		# Match title in parens…
						| ((").+?("))		# or in quotes.
					)?						# Title is optional
					\s*						# Optional whitespace
				(\))
			 )</string>
			<key>name</key>
			<string>meta.link.inline.markdown</string>
		</dict>
		<key>link-ref</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)([^\]]*+)(\])</string>
			<key>name</key>
			<string>meta.link.reference.markdown</string>
		</dict>
		<key>link-ref-literal</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)(\])</string>
			<key>name</key>
			<string>meta.link.reference.literal.markdown</string>
		</dict>
		<key>list-paragraph</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G\s+(?=\S)</string>
					<key>end</key>
					<string>^\s*$</string>
					<key>name</key>
					<string>meta.paragraph.list.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.list_item.markdown</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Match the list punctuation</string>
							<key>match</key>
							<string>^\s*([*+-]|[0-9]+\.)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>raw</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(`+)([^`]|(?!(?&lt;!`)\1(?!`))`)*+(\1)</string>
			<key>name</key>
			<string>markup.raw.inline.markdown</string>
		</dict>
		<key>separator</key>
		<dict>
			<key>match</key>
			<string>\G[ ]{,3}([-*_])([ ]{,2}\1){2,}[ \t]*$\n?</string>
			<key>name</key>
			<string>meta.separator.markdown</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.egamebook</string>
	<key>uuid</key>
	<string>15E11E8B-D755-49FA-BC89-55092A84D3D6</string>
</dict>
</plist>
